spring:
  datasource:
    # driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:mysql://183.237.21.252:13306/ypzx_db
    username: root
    password: 123qweQWE
  
    hikari:
      idle-timeout: 280000
      validation-timeout: 3000
      connection-test-query: SELECT 1 FROM DUAL
      max-lifetime: 300000
      maximum-pool-size: 35 

